version: "3.8"

services:
  gazebo:
    build: ./docker
    container_name: gazebo_class
    volumes:
      - ./:/workspace
    environment:
      - GZ_SIM_RESOURCE_PATH=/workspace/models:/workspace/worlds:/usr/share/gz
    ports:
      - "6080:80"
    tty: true
    stdin_open: true
