services:
  gazebo:
    build: ./docker
    container_name: gazebo_class
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - GZ_SIM_RESOURCE_PATH=/workspace/models:/workspace/worlds:/usr/share/gz
    network_mode: host
    privileged: true
