version: "3.8"

services:
  gazebo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gazebo_class
    volumes:
      - ../:/workspace
    environment: []
    ports:
      - "6080:80"
    tty: true
    stdin_open: true
