services:
  gazebo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gazebo_class
    volumes:
      - ../:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    privileged: true
