#!/usr/bin/env python3
"""
racerlib.py — UB Racer client backend.

Handles the WebSocket connection to server.py, message dispatching, and
provides a thread-safe API for student controller scripts.

Students: import this from controller.py — do not edit this file.
"""

import asyncio
import json
import socket
import ssl
import threading
import time

import websockets

# ── Constants ──────────────────────────────────────────────────────────────────

DEVDRIVE = 8  # local_notice severity used for dev-mode drive command output

# ── SSL context (server.py uses a self-signed cert) ───────────────────────────

_SSL_CTX = ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode    = ssl.CERT_NONE


def _auto_server_url(port: int = 8443) -> str:
    """Return the server.py WebSocket URL for this machine."""
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    return f"wss://{ip}:{port}/ws?role=controller"


# ── Racer ──────────────────────────────────────────────────────────────────────

class Racer:
    """
    Backend connection to the UB Racer client server (server.py).

    Callbacks are called from the background event-loop thread.  Keep them
    short and synchronous; schedule expensive work with threading if needed.

    Usage — script (blocking):
        conn = Racer(on_telemetry=my_telem, ...)
        conn.run()                  # blocks until conn.stop() or Ctrl-C

    Usage — interactive / Jupyter (non-blocking):
        conn = Racer(on_telemetry=my_telem, ...)
        conn.start()                # returns immediately
        conn.join()
        ...
        conn.stop()
    """

    def __init__(
        self,
        on_session_start=None,
        on_session_end=None,
        on_telemetry=None,
        on_system_status=None,
        on_confirm_required=None,
        on_params=None,
        on_estop=None,
        dev=False,
        port=8443,
        server=None,
    ):
        """
        Parameters
        ----------
        on_session_start : callable(data), optional
            Called once when a driving session begins.
            data — full session_start payload (carID, mjpegURL, limits, …).
        on_session_end : callable(data), optional
            Called when the session ends for any reason.
            data — {carID, reason}.
        on_telemetry : callable(data), optional
            Called each time car telemetry arrives (~10 Hz during a session).
            data — {carID, timestamp, steering, throttle, compass}.
            Not called in dev mode (no car available).
        on_system_status : callable(data), optional
            Called ~1 Hz with queue and car availability information.
            data — {cars, globalQueuePosition, yourStatus, yourCarID}.
        on_confirm_required : callable(data), optional
            Called when the system asks you to confirm readiness.
            If omitted, the framework auto-confirms on your behalf.
            data — {carID, carName, timeoutSec}.
        on_params : callable(data), optional
            Called when the browser sends new algorithm parameters via the
            Algo Params panel.  data — full algo_params payload.
        on_estop : callable(isDriving: bool), optional
            Called when the browser toggles the E-Stop button.
            isDriving=False means E-Stop is active (stop driving);
            isDriving=True means driving is re-enabled.
            When isDriving=False, racerlib automatically issues drive(0, 0)
            before invoking this callback.
        dev : bool
            Run in dev mode — no host connection required.
            conn.drive() prints commands to the browser console instead of
            sending them to the car.
        port : int, optional
            Port that server.py is listening on.  Default: 8443.
            Ignored if server= is supplied explicitly.
        server : str, optional
            WebSocket URL of server.py.  Auto-detected if omitted.
            Example: "wss://10.0.0.5:8443/ws?role=controller"
        """
        # Callbacks
        self._on_session_start    = on_session_start
        self._on_session_end      = on_session_end
        self._on_telemetry        = on_telemetry
        self._on_system_status    = on_system_status
        self._on_confirm_required = on_confirm_required  # None → auto-confirm
        self._on_params           = on_params
        self._on_estop            = on_estop

        # Config
        self._dev        = dev
        self._server_url = server or _auto_server_url(port)

        # Internal state (only touched from the event-loop thread once started,
        # except _should_stop which is set before scheduling the stop coroutine)
        self._loop           = None   # asyncio.AbstractEventLoop
        self._thread         = None   # threading.Thread
        self._ws             = None   # websockets.WebSocketClientProtocol | None
        self._session_active = False
        self._should_stop    = False

    # ── Public API ─────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Start the background event loop.  Returns immediately."""
        if self._thread is not None:
            return
        self._loop   = asyncio.new_event_loop()
        self._thread = threading.Thread(target=self._thread_main, daemon=True)
        self._thread.start()

    def run(self) -> None:
        """Start the background loop and block until stop() or Ctrl-C."""
        self.start()
        try:
            self._thread.join()
        except KeyboardInterrupt:
            print("\n[racer] Shutting down ...")
            self.stop()
            self._thread.join(timeout=5)

    def stop(self) -> None:
        """Gracefully leave any queue/session, then shut down."""
        self._schedule(self._graceful_stop())

    def join(self, car_preference: str = None) -> None:
        """Join the car queue.

        Parameters
        ----------
        car_preference : str, optional
            ID of the car you would prefer (e.g. "car1").
            Leave as None to accept any available car.
        """
        payload = {"carPreference": car_preference} if car_preference else None
        self._schedule(self._send_user_request("join", payload))

    def leave(self) -> None:
        """Leave the queue (or exit a running session)."""
        self._schedule(self._send_user_request("exit"))

    def confirm(self) -> None:
        """Confirm readiness when the system asks."""
        self._schedule(self._send_user_request("confirm"))

    def user_request(self, action: str, payload: dict = None) -> None:
        """Send a queue management request.

        Parameters
        ----------
        action : str
            "join", "exit", or "confirm".
        payload : dict, optional
            Extra fields merged into the message (e.g. {"carPreference": "car1"}).
        """
        self._schedule(self._send_user_request(action, payload))

    def drive(self, steering: float, throttle: float) -> None:
        """Send a drive command.

        In a live session the command is forwarded to the car.
        In dev mode the command is printed to the browser console.

        Parameters
        ----------
        steering : float
            User scale [-100, +100]. Negative = left, positive = right.
            The car maps this proportionally to its hardware steering range.
        throttle : float
            User scale [-100, +100]. Negative = reverse, positive = forward.
            The car maps this proportionally to its hardware throttle range.
        """
        self._schedule(self._send_drive(steering, throttle))

    def set_camera_url(self, url: str) -> None:
        """Send the camera stream URL to the browser for display.

        Call this from on_session_start after your camera stream is ready.

        Parameters
        ----------
        url : str
            Publicly reachable MJPEG stream URL, e.g.
            "https://192.168.0.10:8001/stream".
        """
        self._schedule(self._send_camera_url(url))

    def notice(self, severity: int, text: str) -> None:
        """Send a message to the browser console (index.html notices panel).

        Severity constants:
            0 EMERGENCY   1 ALERT   2 CRITICAL   3 ERROR
            4 WARNING     5 NOTICE  6 INFO       7 DEBUG
        """
        self._schedule(self._send_notice(severity, text))

    def start_dev_session(
        self,
        camera_url: str,
        steering_limits: tuple = (-100, 100),
        throttle_limits: tuple = (-100, 100),
        time_limit_sec: float = None,
    ) -> None:
        """Manually start a dev-mode session with a custom camera stream.

        Only available when dev=True.  Synthesises a session_start event and
        invokes on_session_start with a fake payload so your control code can
        run without a real car or host.

        Parameters
        ----------
        camera_url : str
            MJPEG stream URL to use as the camera feed.
        steering_limits : (min, max) tuple of float
            Steering limits in user scale [-100, +100].  Default: (-100, 100).
        throttle_limits : (min, max) tuple of float
            Throttle limits in user scale [-100, +100].  Default: (-100, 100).
        time_limit_sec : float, optional
            Session time limit in seconds.  None means no limit.
        """
        if not self._dev:
            print("[racer] start_dev_session() is only available in dev mode.")
            return
        now  = time.time()
        data = {
            "type":             "session_start",
            "carID":            "dev",
            "carIP":            "localhost",
            "wsPort":           0,
            "mjpegURL":         camera_url,
            "sessionToken":     "dev-token",
            "timeLimitSec":     time_limit_sec,
            "steeringLimits":   {"min": steering_limits[0], "max": steering_limits[1]},
            "throttleLimits":   {"min": throttle_limits[0], "max": throttle_limits[1]},
            "cameraIntrinsics": None,
            "startTime":        now,
            "endTime":          now + time_limit_sec if time_limit_sec else None,
        }
        self._schedule(self._dispatch(data))

    # ── Internal: thread / loop bootstrap ─────────────────────────────────────

    def _thread_main(self) -> None:
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._run_loop())

    def _schedule(self, coro) -> None:
        """Schedule a coroutine on the background loop from any thread."""
        if self._loop is None or not self._loop.is_running():
            print("[racer] Warning: call conn.start() before using this method.")
            coro.close()   # discard cleanly to suppress RuntimeWarning
            return
        # If we're already inside the event loop (e.g. called from a callback),
        # use ensure_future; otherwise use the thread-safe variant.
        try:
            running = asyncio.get_running_loop()
        except RuntimeError:
            running = None
        if running is self._loop:
            asyncio.ensure_future(coro, loop=self._loop)
        else:
            asyncio.run_coroutine_threadsafe(coro, self._loop)

    # ── Internal: async run loop ───────────────────────────────────────────────

    async def _run_loop(self) -> None:
        attempt = 0
        while not self._should_stop:
            if attempt == 0:
                print(f"[racer] Connecting to {self._server_url}")
            else:
                print(f"[racer] Reconnecting ...")
            try:
                async with websockets.connect(
                    self._server_url,
                    ssl=_SSL_CTX,
                    additional_headers={"X-Client": "controller"},
                ) as ws:
                    self._ws = ws
                    attempt  = 0
                    print("[racer] Connected.")
                    await self._receive_loop(ws)
            except Exception as e:
                if not self._should_stop:
                    print(f"[racer] Disconnected: {e}.  Retrying in 3s ...")
            finally:
                self._ws = None
            if not self._should_stop:
                attempt += 1
                await asyncio.sleep(3)
        print("[racer] Stopped.")

    # ── Internal: receive / dispatch ───────────────────────────────────────────

    async def _receive_loop(self, ws) -> None:
        async for raw in ws:
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                continue
            await self._dispatch(msg)

    async def _dispatch(self, msg: dict) -> None:
        t = msg.get("type")

        if t == "session_start":
            self._session_active = True
            if self._on_session_start:
                self._on_session_start(msg)

        elif t == "session_end":
            self._session_active = False
            if self._on_session_end:
                self._on_session_end(msg)

        elif t == "telemetry":
            if self._session_active and self._on_telemetry:
                self._on_telemetry(msg)

        elif t == "system_status":
            if self._on_system_status:
                self._on_system_status(msg)

        elif t == "confirm_required":
            if self._on_confirm_required:
                self._on_confirm_required(msg)
            else:
                print(f"[racer] Confirm required for {msg.get('carName')} — auto-confirming.")
                await self._send_user_request("confirm")

        elif t == "algo_params":
            if self._on_params:
                self._on_params(msg)

        elif t == "e_stop":
            is_driving = msg.get("isDriving", True)
            if not is_driving:
                await self._send_drive(0, 0)
            if self._on_estop:
                self._on_estop(is_driving)

        elif t == "host_notice":
            sev = msg.get("severity", 6)
            if sev <= 4:  # WARNING and above
                print(f"[host] ({sev}) {msg.get('text')}")

    # ── Internal: send helpers ─────────────────────────────────────────────────

    async def _send_user_request(self, action: str, payload: dict = None) -> None:
        msg = {"type": "user_request", "action": action}
        if payload:
            msg.update(payload)
        await self._send(msg)

    async def _send_drive(self, steering: float, throttle: float) -> None:
        if self._dev:
            await self._send_notice(
                DEVDRIVE,
                f"drive: steering={steering:.1f}  throttle={throttle:.1f}",
            )
        else:
            await self._send({
                "type":     "drive",
                "steering": float(steering),
                "throttle": float(throttle),
            })

    async def _send_camera_url(self, url: str) -> None:
        await self._send({"type": "camera_url", "url": url})

    async def _send_notice(self, severity: int, text: str) -> None:
        await self._send({"type": "local_notice", "severity": severity, "text": text})

    async def _send(self, msg: dict) -> None:
        if self._ws is not None:
            try:
                await self._ws.send(json.dumps(msg))
            except Exception as e:
                print(f"[racer] send error: {e}")

    # ── Internal: graceful stop ────────────────────────────────────────────────

    async def _graceful_stop(self) -> None:
        self._should_stop = True
        await self._send_user_request("exit")
        if self._ws is not None:
            try:
                await self._ws.close()
            except Exception:
                pass
